## Normalization Problem

In [45]:
#Import numerical python Library
import numpy as np
#Create random 5x5 array
X = np. random. rand(5, 5)
#Function for Normalized Values
Z = (X - X.mean()) /X.std() 
#save Normalized values as X_nomatized. ny
np. save("X_normalized.npy", Z) 
#Print X and Z
print ("Original Value: \n", X, "\n Normalized Value: \n", Z) 
#end

Original Value: 
 [[0.1907362  0.97216806 0.21898438 0.8201767  0.13816586]
 [0.40949616 0.94828986 0.74608051 0.01448733 0.66344152]
 [0.52513009 0.39648703 0.31855252 0.61107132 0.50372864]
 [0.22296194 0.38786999 0.38595267 0.38474052 0.77712486]
 [0.45207678 0.03230963 0.39032108 0.8441497  0.78218564]] 
 Normalized Value: 
 [[-1.0869788   1.79496723 -0.98279862  1.23441815 -1.28085992]
 [-0.28018499  1.70690365  0.96114902 -1.73699035  0.65637372]
 [ 0.1462767  -0.32816307 -0.61558807  0.46323075  0.06734745]
 [-0.96812925 -0.35994301 -0.36701415 -0.3714846   1.0756416 ]
 [-0.12314627 -1.67126113 -0.3509033   1.32283136  1.09430588]]


## Divisible by 3 Problem

In [57]:
import numpy as np

#Create an array of the first 100 positive integers
n = np.arange(1,101)

#Square every element
A_squared = np.square(n)

#Resize into a 10x10 ndarray
A = A_squared.reshape(10,10)

#Determine the elements divisible by 3
Div_by_3 = A[A % 3 == 0]

#Save the result as div_by_3.npy
np.save('div_by_3.npy', Div_by_3)

#Print the output of "A" and "div_by_3"
print("A =\n", A, "\nElements divisible by 3:\n", Div_by_3)

A =
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]] 
Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
